### ISSUE TITLE
Please reply here if you've found new fake IPs

### ISSUE THREAD

**Issue by clowwindy** [clowwindy/ChinaDNS-C#42]
Please provide
1. a list of IPs you've discovered
2. the method or command you used

    dig @8.8.8.8 domain.that.i.used
    ...
    domain.that.i.used.	233	IN	A	37.61.54.158

**Comment by XIAOSpider97** [comment]
最好能把IPv6环境的1.1.1.1 10.10.10.10 20.20.20.20 255.255.255.255也加进去，还有去年一月那个事件的65.49.2.178。
作者可以试试这样：将数据包推迟，让系统认为GFW返回的污染包比包含真实IP的包后到。

**Comment by clowwindy** [comment]
@XIAOSpider97 昨天已经更新了

**Comment by XIAOSpider97** [comment]
又找到三个。。。
107.20.186.211
88.198.69.101
216.87.172.206
我是Windows，不知道怎么dig…

**Comment by aa65535** [comment]
目前来说，使用 iplist 没意义了，而且返回的结果里也有正常网站的。
我昨天用 cron 跑了一夜（一小时获取一次），去重后的结果是 1290 个 ……

**Comment by XIAOSpider97** [comment]
所以说...我目前的解决方案是直接转发非标端口DNS以“完全规避”污染。

**Comment by clowwindy** [comment]
@XIAOSpider97 @aa65535 
1.2.0 已经不需要 iplist 了

**Comment by aa65535** [comment]
@clowwindy 目前还是必须使用 `-l` 指定 iplist, 否则会报错。

**Comment by clowwindy** [comment]
@aa65535  Created #44

**Comment by msxcms** [comment]
发现www.qq.com会被解析到香港IP上（配置的境外DNS用的是日本的），暂时还没发现其他国内域名会出这个问题

;; ANSWER SECTION:
www.qq.com.             270     IN      A       202.55.10.190
www.qq.com.             270     IN      A       202.55.10.189

;; Query time: 72 msec
;; SERVER: 192.168.1.1#5353(192.168.1.1)

**Comment by yuhaaitao** [comment]
youtub能打开，看不了视频，这个怎么弄呀
