### ISSUE TITLE
Make iplist optional

### ISSUE THREAD

**Issue by clowwindy** [clowwindy/ChinaDNS-C#44]

**Comment by hgl** [comment]
比较好奇，没有了iplist，如何判断返回的结果是否被污染？

最近好多域名返回的污染ip是不重复的，我以为没有办法检测是否被污染了。

**Comment by clowwindy** [comment]
If an experienced human can tell the difference, so does a program.

**Comment by hgl** [comment]
看了一下源代码，好像原理是直接丢弃国内DNS返回的国外IP，然后等待国外DNS的返回结果。国外DNS返回IP时如果只有一条结果，延时等待下一个返回。

顺便提交一个bug，好像如果国内DNS返回国内IP，只有一条结果，也会被延时。

目前来看是很棒的的方法，但是什么时候系统升级，污染的IP里开始出现多条结果，这个方法就失效了。（短时间内应该不会失效，不过既然系统能从返回固定IP升级到返回不固定IP，再次升级应该也不是太麻烦的事。）

受到你的启发，我觉得如果系统真的开始这样做，我们可以设置路由表，让国外DNS的查询走VPN。这样不论系统怎么改结果都不会被污染了。

**Comment by clowwindy** [comment]
Don't teach them.
