### ISSUE TITLE
qq域名会被返回到国外IP上

### ISSUE THREAD

**Issue by msxcms** [clowwindy/ChinaDNS-C#45]
发现www.qq.com会被解析到香港IP上（配置的境外DNS用的是日本的），暂时还没发现其他国内域名会出这个问题

;; ANSWER SECTION:
www.qq.com.             270     IN      A       202.55.10.190
www.qq.com.             270     IN      A       202.55.10.189

;; Query time: 72 msec
;; SERVER: 192.168.1.1#5353(192.168.1.1)

国内DNS返回的是正常的

;; ANSWER SECTION:
www.qq.com.             291     IN      A       61.135.157.156

;; Query time: 13 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)

另外发现 1.2.0 在openwrt下一直会占用10%左右的CPU

**Comment by clowwindy** [comment]
新的策略下可能会有一部分国内域名误判到国外，过段时间再想办法。CPU 的问题找到原因了，过会儿修复。

**Comment by clowwindy** [comment]
1.2.1 以修复 CPU 问题。
