### ISSUE TITLE
使用配置文件或者uci

### ISSUE THREAD

**Issue by lsylsy2** [clowwindy/ChinaDNS-C#47]
RT，目前的设置（和是否使用iptables）都是在init.d中设置，修改是否复杂暂且不论，在升级时文件会被覆盖是一个问题。
个人例子：
1、需要注释掉iptables以使用dnsmasq（dnsmasq也是一个推荐选项），然后这个修改需要先stop（以在iptables中删除redirect）、再修改、再start；
2、114dns在我的ISP表现效果不佳，结合chinadns的新策略，导致最终效果相当于等待（0.3秒）后一定返回国外DNS结果；同样，这项的修改我需要每次更新都进行处理。

另外，监听5353然后用iptables转发并不符合软件的正常逻辑，结果就是原53端口的DNS服务器正常运行但是被“掐断”；更加自然的逻辑是在“监听5353，更改现有程序如dnsmasq的上游”和“监听53，让用户关掉现有的dns服务”中二选一。

**Comment by clowwindy** [comment]
推荐用 @aa65535 维护的包，直接在 luci 里配置，非常方便。

https://github.com/aa65535/openwrt-dist-luci
